### ISSUE TITLE
Repository doesn't contain code

### ISSUE THREAD

**Issue by lesderid** [martinus/web-keto-calculator#1]
It looks like the repository currently doesn't contain the actual code of the calculator. 

(I would like to adapt it a bit to my needs, so any license (including e.g. AGPL) or no license is fine for me personally, it's only for offline use.)

**Comment by martinus** [comment]
The calculator is proprietary and not open source, I'm just hosting it here.

**Comment by lesderid** [comment]
Okay, thanks anyway!
